# ~/.config/starship.toml

# Use custom format
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](#FFFFFF)
[â”‚](#FFFFFF)$memory_usage$directory$rust$package
[â””â”€>](#FFFFFF) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false


[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ"
style = "#FFFFFF"

[directory]
disabled = false
style = "#666666"
